import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import GoogleAdsense from "@/components/GoogleAdsense";
import HomeNav from "@/components/HomeNav";
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <GoogleAdsense />
      </head>
      <body className={`${roboto.variable} antialiased`}>
        <div className="flex w-full flex-col items-center justify-center">
          <HomeNav />
          {children}
        </div>
      </body>
    </html>
  );
}
